FROM node:14.16.1-slim AS build
WORKDIR /app
COPY package.json ./
COPY yarn.lock ./
RUN ["yarn", "install"]
COPY . .
ENV NODE_ENV=production
RUN ["yarn", "build:web"]

FROM nginx:alpine
WORKDIR /app

# Install bash
RUN apk add bash --no-cache

# Update nginx config
COPY nginx /etc/nginx

# Copy files necessary for syncing runtime environment variables
COPY envToJson.sh .
COPY .env.runtime .
COPY 99-env2json.sh /docker-entrypoint.d/
RUN chmod +x envToJson.sh & chmod +x /docker-entrypoint.d/99-env2json.sh

# Copy SPA to nginx
COPY --from=build /app/packages/ecs-editor/dist /usr/share/nginx/html/
