version: '3.7'

services:
  db:
    container_name: db
    image: "postgres:13"
    restart: "always"
    ports:
      - 4002:4002
    command: -p 4002
    environment:
      POSTGRES_USER: "ecs"
      POSTGRES_PASSWORD: "ecs"
  api:
    depends_on:
      - db
    restart: "always"
    container_name: api
    image: docker.pkg.github.com/ksandin/ecs/ecs_api:latest
    ports:
      - 4001:4001
    environment:
      POSTGRES_URL: "postgres://ecs:ecs@db:4002/ecs"
      ECS_API_PORT: 4001
      ECS_API_CORS_ORIGIN: "https://ecseditor.xyz"
  web:
    container_name: web
    image: docker.pkg.github.com/ksandin/ecs/ecs_web:latest
    environment:
      ECS_API_URL: https://ecseditor.xyz:4001
    ports:
      - 4000:4000
  proxy:
    container_name: proxy
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
