version: '3.7'

x-var-api: &API
  build:
    context: .
    dockerfile: Dockerfile.api
x-var-web: &WEB
  build:
    context: .
    dockerfile: Dockerfile.web

services:
  db:
    image: "postgres:13-alpine"
    restart: "always"
    command: -p 4002
    environment:
      POSTGRES_USER: "ecs"
      POSTGRES_PASSWORD: "ecs"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  api:
    <<: *API
    depends_on:
      - db
    restart: "always"
    environment:
      POSTGRES_URL: "postgres://ecs:ecs@db:4002/ecs"
      ECS_API_PORT: 4001
      ECS_API_CORS_ORIGIN: "https://ecseditor.xyz"
  web:
    <<: *WEB
    environment:
      NGINX_PORT: 4000
      ECS_API_URL: https://api.ecseditor.xyz
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      DISABLE_IPV6: 'true'
    volumes:
      - proxy-data:/data
      - letsencrypt-data:/etc/letsencrypt

volumes:
  ? postgres-data
  ? proxy-data
  ? letsencrypt-data
