version: '3.7'

services:
  db:
    container_name: db
    image: "postgres:13"
    restart: "always"
    ports:
      - 3002:3002
    command: -p 3002
    environment:
      POSTGRES_USER: "ecs"
      POSTGRES_PASSWORD: "ecs"
  api:
    depends_on:
      - db
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.api
    command: yarn run:api
    ports:
      - 3001:3001
    environment:
      POSTGRES_URL: "postgres://ecs:ecs@db:3002/ecs"
      ECS_API_PORT: 3001
      ECS_API_CORS_ORIGIN: "https://ksandin-ecs-editor.surge.sh"
# web server disabled. Using surge.sh instead (see github workflow)
#  web:
#    container_name: web
#    build:
#      args:
#        run: 'export NODE_ENV=production && export ECS_API_URL=http://localhost:3001'
#      context: .
#      dockerfile: Dockerfile.web
#    command: serve packages/ecs-editor/dist -l 80 -s
#    ports:
#      - 80:80
