version: '3.7'

services:
  db:
    image: "postgres:13-alpine"
    restart: "always"
    ports:
      - 4002:4002
    command: -p 4002
    environment:
      POSTGRES_USER: "ecs"
      POSTGRES_PASSWORD: "ecs"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  api:
    depends_on:
      - db
    restart: "always"
    image: ghcr.io/ksandin/ecs/ecs_api:latest
    ports:
      - 4001:4001
    environment:
      POSTGRES_URL: "postgres://ecs:ecs@db:4002/ecs"
      ECS_API_PORT: 4001
      ECS_API_CORS_ORIGIN: "https://ecseditor.xyz"
  web:
    image: ghcr.io/ksandin/ecs/ecs_web:latest
    environment:
      ECS_API_URL: https://ecseditor.xyz:4001
    ports:
      - 4000:4000
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      DISABLE_IPV6: 'true'
    volumes:
      - proxy-data:/data
      - letsencrypt-data:/etc/letsencrypt

volumes:
  postgres-data:
  proxy-data:
  letsencrypt-data:
