name: CI
on:
  push:
    branches: [ docker ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: yarn install
      - name: Run tests
        run: yarn test
      - name: Run docker-compose in DO droplet
        uses: appleboy/ssh-action@master
        with:
          host: ecseditor.xyz
          username: ${{ secrets.ssh_username }}
          password: ${{ secrets.ssh_password }}
          script: rm -rf ecs && git clone https://github.com/ksandin/ecs.git && cd ecs && docker-compose up --build -d --force-recreate --remove-orphans
